In [5]:
import numpy as np
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
import numpy as np
#Create a null vector of size 10 but the fifth value which is 1.

a = np.zeros(10)

a[4] = 1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

arr = np.random.rand(a, b)
print("Generated array:")
print(arr)
print("Average of the array:")
print(np.mean(arr))

Generated array:
[[0.45067712 0.62694197 0.88491967 0.32158171]
 [0.2944534  0.55338335 0.85235864 0.91949807]]
Average of the array:
0.6129767402024183


In [13]:
#Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
def create_array(a, b):
    a = np.zeros((a, b), dtype=int)
    a[0, :] = 1
    a[-1, :] = 1
    a[:, 0] = 1
    a[:, -1] = 1
    return a
print(create_array(4,4))


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [14]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.random.rand(10)
print(vector)

[0.00900943 0.12209487 0.26385709 0.72116439 0.66959305 0.78160897
 0.64754788 0.55193087 0.17292073 0.46809429]


In [17]:
#Create a 5x5 matrix with row values ranging from 0 to 4.
matrix = np.arange(5).reshape(5, 1) * np.ones((1, 5))
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [18]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr = np.arange(6*7*8).reshape(6, 7, 8)
index = np.unravel_index(99, arr.shape)
print(index)

(np.int64(1), np.int64(5), np.int64(3))


In [20]:
#Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.
random_cords = np.random.randint(1, 101, size=(10, 2))
given_point = np.array([50, 50])
distances = np.sqrt(np.sum((random_cords - given_point) ** 2, axis=1)).astype(int)
print("Random coordinates:\n", random_cords)
print("Distances from the given point:\n", distances)


Random coordinates:
 [[ 3 89]
 [91 82]
 [45 99]
 [76 37]
 [23 30]
 [27 86]
 [96 10]
 [42 41]
 [23 40]
 [34 49]]
Distances from the given point:
 [61 52 49 29 33 42 60 12 28 16]
